/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpledraw;

import MVC.CustomListModel;
import MVC.MyObservable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JList;

/**
 *
 * @author kerbrase
 */
public class SecondaryFrame extends javax.swing.JFrame implements MVC.MyObserver {

    CustomListModel listModel;

    /**
     * Creates new form SecondaryFrame2
     *
     * @param myDrawing
     */
    public SecondaryFrame(Drawing myDrawing) {
        listModel = new CustomListModel();
        initComponents();
        myDrawing.addObserver(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(listModel);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(MyObservable o) {
        Drawing myDrawing = (Drawing) o;
        List<String> strings = new ArrayList<>();
        for (Shape s : myDrawing.getMyShapes()) {
            strings.add(s.toString());
        }
        String[] stringss = strings.toArray(new String[0]);
        listModel.setContent(stringss);
        repaint();
    }
}
